// REST Client
//busca retorno sobre a APi
GET http://localhost:3000/
content-type: application/json
###
GET http://localhost:3000/cadastrados
content-type: application/json
###
// Cadastra no db
POST http://localhost:3000/cadastrar
content-type: application/json

{
  "name": "lucas6-supabase",
  "email": "lucas6@example.com"
}

###
//Altera uma cadastro
PATCH http://localhost/3000/modify_cadastro
content-type: application/json

{
     " recipitientId": "23456726",
    " content": "dodowujggwhwhw",
    "category ": "dwyhd"

}
###